{% set name = "neovim" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a6a0e7a5b4433bf4e6ddcbc5c5ff44170be7d84259d002b8e8d8fb4ee78af60f

build:
  noarch: python
  number: 4
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pynvim

test:
  requires:
    - python {{ python_min }}
  imports:
    - neovim
    - neovim.api

about:
  home: http://github.com/neovim/python-client
  license: Apache-2.0
  license_family: Apache
  license_file: 'LICENSE'
  summary: 'Python client to neovim'

  description: |
    Python client to neovim
  dev_url: https://github.com/neovim/python-client

extra:
  recipe-maintainers:
    - curtisalexander
    - xhochy
