{% set name = "neovim" %}
{% set version = "0.3.1" %}
{% set sha256 = "a6a0e7a5b4433bf4e6ddcbc5c5ff44170be7d84259d002b8e8d8fb4ee78af60f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - msgpack-python >=0.5.0
    - greenlet
    - trollius  # [py27]
    - pyuv >=1.0.0  # [win]

test:
  imports:
    - neovim
    - neovim.api
    - neovim.msgpack_rpc
    - neovim.msgpack_rpc.event_loop
    - neovim.plugin

about:
  home: http://github.com/neovim/python-client
  license: Apache-2.0
  license_family: Apache
  license_file: 'LICENSE'
  summary: 'Python client to neovim'

  description: |
    Python client to neovim
  dev_url: https://github.com/neovim/python-client

extra:
  recipe-maintainers:
    - curtisalexander
    - xhochy
