appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: AmAZaVzHBu1SiVi8NKAM2AZwUcku7WfVjqOV3uC1RmYE8hyKICx7sFBDGAFSMcKSxGWzFRVjVHOUOV+DCTzyBNP/2L80591amrk7FjRyl3qoXL67aJOe8LzF1yiH0wmnV7FeYOA9rtsDt1UZ8BAaUeaLZ9eeZLO0ULCHIDaOV/OAMjc5OMW6oUyqeowlw9ibeCy0ykgYOUZEFYBBAmiBVRjnu5Q48rZFasdmd+6ov4DXzJeC+Wfm45ICJ66ltx+kE647BuuWhZJLnV/YUe+1Lsa3+H49f3AvHYYUpEzQ8YgUDGnd6K71w9aFR6Hc4U4w5+pG/zEZZl6pm3tsLhcqEseapgJtSnJXPnOy0eijQqzgWA14iCw0iPpNckLKRgxZ+X2588iR2w6cyCYRmxQGrFFJsPTZyBe2KSa4yp2u3wZYXca9eQgi5yximj/79OT52ME9nlu5J3CzLYAgAZF1NK+oPTjiozB2TzuX5BRrmMiIPNLKcVG0oMmT1BiP9+WR+PkVSxlPR9H+FQoOhY0tLnQWBcb3DaxGOYBqXtXNIIESQr0nH8++fHznBTukLCbm7d0qybX1DG+PmYqj3MWuIEMdzBPRX9euB7w+imwacoj637om/q8iCBTbEknCROAveWmsPj7qQWNIEuNxv+Ol3dKMX4dh8y8y2aoqNguCZJw=}
