travis:
  secure:
    BINSTAR_TOKEN: ZAglbqquSahOwBl2KzkmekI1bqQ+IpiO/Jr9LFwfTuuhaoaHotyK/gxDNSfZVrDrPASAOVPMYrRmaPdeAJtdcuYvOI0OMNkEv7v6TpbPw8TdZ7Dj56YGbtxWwcUS7cz6ElLB7E+NR65XnedtJ4qTtxhi5FwACTK08OqfEqKtJ9KDROd/TVJXB8g9ZHgCaYuzc1cJ5+cQZ16mSUSxRQ+sO+wxEiiEMMvMrasRt8ieIE8GOJTlfIw++UOWnlMUgogDbTHCFQtvUAuMxBQI4E5gctLp1OTmnsE7wReeOQlJPLf8R89aizOCdPRtiHmdsAzXGIHe2itcLtHzXOTOJyskOoatB6Vv0Lvz/S6/MIbVyKwsVrLLQkhHmwpZId/g9ILYF2F9phb3viegBN2O/B7HKsFOnloRkvXgFNpVIgfFnjaXL8EJ/PQQhs7VplbGotlKNJg0IMXOIhvl4sMmsNrt+eNbybIBDbbujFdroPGP58c61AUE/Ogpin+jv9ybuOTozUEFAtdl65LR9TXv/YZta0vtryUwAMcc7xnn8nkRWk7W+JE5LDEuDn/frLf5C8HzlCa5OWKhWoqFoFx9wQhJ9w+7W+WvjxG9SJZ4jZDvDri/hDKnIHWy2wRG8a7qXqiyGJxFDYy7VMxBDNJoWISQRGleVImjlVCV1gYFWbp8np0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
